services:  
  cuda_base:
    build:
      context: ../
      dockerfile: dockerfiles/ros.dockerfile
      args:
        BASE_IMAGE: nvidia/cuda:12.2.2-devel-ubuntu22.04
    image: roborregos/vsss:ros2_cuda_base