services:
  vsss_gpu:
    build:
      context: ../
      dockerfile: dockerfiles/vsss.dockerfile
      args:
        BASE_IMAGE: roborregos/vsss:ros2_cuda_base
        SHOULD_USE_CUDA: --index-url https://download.pytorch.org/whl/cu121
    image: roborregos/vsss:vsss_gpu
    container_name: vsss_gpu
    gpus: all
    environment:
      - DISPLAY=${DISPLAY}
      - TERM=xterm-256color
      - QT_X11_NO_MITSHM=1
      - QT_DEBUG_PLUGINS=1
    volumes:
      - ../../:/workspace
      - /dev:/dev
      - /dev/video0:/dev/video0
      - /tmp:/tmp
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./build:/workspace/build
      - ./install:/workspace/install
      - ./log:/workspace/log
    devices:
      - /dev/dri:/dev/dri
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
      - /dev/video2:/dev/video2
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    working_dir: /workspace
    command: >
      bash -c "/bin/bash "