<robot xmlns:xacro="http://ros.org/wiki/xacro" name="vsss_robot">

    <!-- Parameters -->

    <xacro:arg name='robot_name' default="robot"/>
    <xacro:arg name='dominant_plate_color' default="BlueLaser"/>
    <xacro:arg name='small_plate_1' default="Green"/>
    <xacro:arg name='small_plate_2' default="Turquoise"/>
    <xacro:property name="wheel_radius" value="0.035"/>
    <xacro:property name="wheel_width" value="0.005"/>
    <xacro:property name="wheel_separation" value="0.075"/>
    <xacro:property name="body_size" value="0.075"/>

    <!-- Base Link -->
    <link name="$(arg robot_name)_base_link">
        <visual>
            <origin xyz="0 0 ${body_size / 2}" rpy="0 0 0"/>
            <geometry>
                <box size="${body_size} ${body_size} ${body_size}"/>
            </geometry>
            <material name="Gray">
                <color rgba="0.6 0.6 0.6 1.0"/>
            </material>
        </visual>
        <collision>
            <origin xyz="0 0 ${body_size *0.1}" rpy="0 0 0"/>
            <geometry>
                <box size="${body_size} ${body_size} ${body_size*0.4}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="1.0"/>
            <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
        </inertial>
    </link>

    <!-- Left Wheel -->
    <link name="left_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
            <origin rpy="0 0 0"/>
            <material name="Black">
                <color rgba="0.0 0.0 0.0 1.0"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
            <origin rpy="0 0 0"/>
        </collision>
        <inertial>
            <mass value="0.2"/>
            <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
        </inertial>
    </link>

    <!-- Right Wheel -->
    <link name="right_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
            <origin rpy="0 0 0"/>
            <material name="Black">
                <color rgba="0.0 0.0 0.0 1.0"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
            <origin rpy="0 0 0"/>
        </collision>
        <inertial>
            <mass value="0.2"/>
            <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
        </inertial>
    </link>

    <!-- Big plate-->
    <link name="dominant_plate_link">
        <visual>
            <geometry>
                <box size="${(body_size / 2) * 0.95} ${(body_size) * 0.95} 0.01"/>
            </geometry>
            <origin rpy="0 0 0"/>
            <material name="Gray">
                <color rgba="0.6 0.6 0.6 1.0"/>
            </material>
        </visual>
    </link>

    <!-- Small plate 1-->
    <link name="small_plate_1_link">
        <visual>
            <geometry>
                <box size="${(body_size / 2) * 0.9} ${(body_size / 2) * 0.9} 0.009"/>
            </geometry>
            <origin rpy="0 0 0"/>
            <material name="Gray">
                <color rgba="0.6 0.6 0.6 1.0"/>
            </material>
        </visual>
    </link>

    <!-- Small plate 2-->
    <link name="small_plate_2_link">
        <visual>
            <geometry>
                <box size="${(body_size / 2) * 0.9} ${(body_size / 2) * 0.9} 0.009"/>
            </geometry>
            <origin rpy="0 0 0"/>
            <material name="Gray">
                <color rgba="0.6 0.6 0.6 1.0"/>
            </material>
        </visual>
    </link>

    <!-- Wheel Joints -->
    <joint name="left_wheel_joint" type="continuous">
        <parent link="$(arg robot_name)_base_link"/>
        <child link="left_wheel_link"/>
        <origin xyz="0 -${wheel_separation/2} ${body_size*0.35}" rpy="1.57 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>

    <joint name="right_wheel_joint" type="continuous">
        <parent link="$(arg robot_name)_base_link"/>
        <child link="right_wheel_link"/>
        <origin xyz="0 ${wheel_separation/2} ${body_size*0.35}" rpy="1.57 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>

    <joint name="dominant_plate_joint" type="fixed">
        <parent link="$(arg robot_name)_base_link"/>
        <child link="dominant_plate_link"/>
        <origin xyz="${-body_size / 4} 0.0 ${body_size + 0.01}" rpy="0.0 0.0 0.0"/>
        <axis xyz="0 0 1"/>
    </joint>

    <joint name="small_plate_1_joint" type="fixed">
        <parent link="$(arg robot_name)_base_link"/>
        <child link="small_plate_1_link"/>
        <origin xyz="${body_size / 4} ${body_size / 4} ${body_size + 0.01}" rpy="0.0 0.0 0.0"/>
        <axis xyz="0 0 1"/>
    </joint>

    <joint name="small_plate_2_joint" type="fixed">
        <parent link="$(arg robot_name)_base_link"/>
        <child link="small_plate_2_link"/>
        <origin xyz="${body_size / 4} ${-body_size / 4} ${body_size + 0.01}" rpy="0.0 0.0 0.0"/>
        <axis xyz="0 0 1"/>
    </joint>


    <ros2_control name="GazeboSystem" type="system">
        <hardware>
            <plugin>gazebo_ros2_control/GazeboSystem</plugin>
        </hardware>

        <joint name="left_wheel_joint">
            <command_interface name="velocity"/>
            <state_interface name="velocity"/>
        </joint>

        <joint name="right_wheel_joint">
            <command_interface name="velocity"/>
            <state_interface name="velocity"/>
        </joint>
    </ros2_control>

    <!-- Gazebo Diff Drive Plugin -->
    <gazebo>
        <plugin name="$(arg robot_name)_diff_drive_controller" filename="libgazebo_ros_diff_drive.so">
        <ros>
            <namespace>/$(arg robot_name)</namespace>
        </ros>
            <left_joint>left_wheel_joint</left_joint>
            <right_joint>right_wheel_joint</right_joint>
            <wheel_separation>0.3</wheel_separation>
            <wheel_radius>0.05</wheel_radius>
            <wheel_diameter>0.1</wheel_diameter>
            <publish_odom>true</publish_odom>
            <odom_topic>odom</odom_topic>
            <cmd_vel_topic>cmd_vel</cmd_vel_topic>
            <robot_base_frame>$(arg robot_name)_base_link</robot_base_frame>
        </plugin>
    </gazebo>

    <!-- Gazebo Material -->
    <gazebo reference="$(arg robot_name)_base_link">
        <material>Gazebo/Black</material>
    </gazebo>
    <gazebo reference="left_wheel_link">
        <material>Gazebo/Black</material>
    </gazebo>
    <gazebo reference="right_wheel_link">
        <material>Gazebo/Black</material>
    </gazebo>

    <gazebo reference="dominant_plate_link">
        <material>Gazebo/$(arg dominant_plate_color)</material>
    </gazebo>

    <gazebo reference="small_plate_1_link">
        <material>Gazebo/$(arg small_plate_1)</material>
    </gazebo>

    <gazebo reference="small_plate_2_link">
        <material>Gazebo/$(arg small_plate_2)</material>
    </gazebo>


</robot>
